import {db,uid} from './db'; import type {Asset,EventType,InstrumentFamily,MaintenanceEvent,Reminder,StringInstallation,UsualString} from './types';
const now=()=>new Date().toISOString();
export async function createAsset(input:{profileType:'instrument'|'bow';name:string;maker?:string;instrumentFamily?:InstrumentFamily;customPositions?:string[]}):Promise<Asset>{const stamp=now();const asset:Asset={...input,id:uid(),status:'active',createdAt:stamp,updatedAt:stamp};await db.assets.add(asset);return asset}
export async function setArchived(id:string,archived:boolean){await db.assets.update(id,{status:archived?'archived':'active',updatedAt:now()})}
export type InstallInput=Omit<StringInstallation,'id'|'assetId'|'maintenanceEventId'|'installedDate'|'removedDate'> & {position:string};
export async function logStringChange(assetId:string,date:string,strings:InstallInput[],meta:{notes?:string;cost?:number;reminderDate?:string}={}){return db.transaction('rw',[db.events,db.installations,db.reminders],async()=>{const stamp=now(),eventId=uid();const event:MaintenanceEvent={id:eventId,assetId,eventType:'string-change',date,notes:meta.notes,cost:meta.cost,createdAt:stamp,updatedAt:stamp};await db.events.add(event);for(const string of strings){const active=await db.installations.where('[assetId+position]').equals([assetId,string.position]).filter(x=>!x.removedDate).toArray();await Promise.all(active.map(x=>db.installations.update(x.id,{removedDate:date})));await db.installations.add({...string,id:uid(),assetId,maintenanceEventId:eventId,installedDate:date});}if(meta.reminderDate)await db.reminders.add({id:uid(),assetId,maintenanceEventId:eventId,title:'Consider your next string change',dueDate:meta.reminderDate,status:'active',createdAt:stamp});return event})}
export async function currentSetup(assetId:string){return db.installations.where('assetId').equals(assetId).filter(x=>!x.removedDate).sortBy('position')}
export async function logMaintenance(assetId:string,eventType:EventType,workType:string,date:string,meta:{provider?:string;cost?:number;notes?:string;reminderDate?:string}={}){const stamp=now(),event:MaintenanceEvent={id:uid(),assetId,eventType,workType,date,provider:meta.provider,cost:meta.cost,notes:meta.notes,createdAt:stamp,updatedAt:stamp};await db.transaction('rw',[db.events,db.reminders],async()=>{await db.events.add(event);if(meta.reminderDate)await db.reminders.add({id:uid(),assetId,maintenanceEventId:event.id,title:eventType==='bow-rehair'?'Consider a bow rehair':'Maintenance reminder',dueDate:meta.reminderDate,status:'active',createdAt:stamp})});return event}
export async function updateEvent(id:string,patch:Partial<Pick<MaintenanceEvent,'date'|'provider'|'cost'|'notes'|'workType'>>){const event=await db.events.get(id);if(!event)return;if(event.eventType==='string-change'&&patch.date&&patch.date!==event.date)throw new Error('String-change dates cannot be edited; delete and re-log the change.');await db.events.update(id,{...patch,updatedAt:now()})}
export async function deleteEvent(id:string){await db.transaction('rw',[db.events,db.installations,db.reminders],async()=>{const event=await db.events.get(id);if(!event)return;if(event.eventType==='string-change'){const installed=await db.installations.where('maintenanceEventId').equals(id).toArray();for(const item of installed){const later=await db.installations.where('[assetId+position]').equals([item.assetId,item.position]).filter(x=>x.installedDate>item.installedDate&&x.maintenanceEventId!==id).count();if(later)throw new Error('This string change has later replacements and cannot be deleted.');const prior=await db.installations.where('[assetId+position]').equals([item.assetId,item.position]).filter(x=>x.id!==item.id&&!!x.removedDate&&x.removedDate===item.installedDate).toArray();await Promise.all(prior.map(x=>db.installations.update(x.id,{removedDate:undefined})));await db.installations.delete(item.id)}}await db.reminders.where('maintenanceEventId').equals(id).delete();await db.events.delete(id)})}
export async function saveUsualSetup(assetId:string){const strings=await currentSetup(assetId);await db.usualSetups.put({assetId,strings:strings.map(({position,brand,model,tensionOrGauge})=>({position,brand,model,tensionOrGauge} as UsualString)),updatedAt:now()})}
export async function seedDevelopment(){if(!import.meta.env.DEV)throw new Error('Seed is available in development only');if(await db.assets.count())return;const cello=await createAsset({profileType:'instrument',name:'Main cello',instrumentFamily:'cello'});await logStringChange(cello.id,'2025-11-10',[{position:'A',brand:'Larsen',model:'Original'},{position:'D',brand:'Larsen',model:'Original'},{position:'G',brand:'Thomastik-Infeld',model:'Spirocore'},{position:'C',brand:'Thomastik-Infeld',model:'Spirocore'}]);const bow=await createAsset({profileType:'bow',name:'Primary bow'});await logMaintenance(bow.id,'bow-rehair','Rehair','2026-03-15',{reminderDate:'2026-09-15'})}
